// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H

#define LAYOUT_unix_119_ansi( \
    K00, K01, K32, K42, K33, K43, K24, K34, K25, K35, K16, K96, K106, K77, K87, K58, K68, K09, K99, K010, K910, \
    K100, K10, K11, K101, K22, K52, K23, K53, K14, K44, K15, K45, K06, K26, K86, K07, K67, K97, K48, K78, K19, K89, K110, K810, \
    K90 , K20, K21, K91, K12, K62, K13, K63, K04, K54, K05, K55, K105, K36, K76, K17, K107, K38, K88, K29, K79, K210, K710, \
    K80, K30, K31, K81, K02, K72, K03, K73, K103, K64, K104, K65, K95, K46, K27, K39, K69, K310, \
    K70, K40, K41, K71, K82, K102, K83, K93, K74, K94, K75, K85, K56, K37, K28, K49, K59, K410, K610, \
    K60, K50, K51, K61, K92, K84, K66, K47, K57, K08, K18, K98, K108, K510 \
) { \
    {K00, K01, K32, K42, K33, K43, K24, K34, K25, K35, K16, K96, K106, K77, K87, K58, K68, K09, K99, K010, K910}, \
    {K100, K10, K11, K101, K22, K52, K23, K53, K14, K44, K15, K45, K06, K26, K86, K07, K67, K97, K48, K78, K19, K89, K110, K810}, \
    {K90 , K20, K21, K91, K12, K62, K13, K63, K04, K54, K05, K55, K105, K36, K76, K17, K107, K38, K88, K29, K79, K210, K710}, \
    {K80, K30, K31, K81, K02, K72, K03, K73, K103, K64, K104, K65, K95, K46, K27, K39, K69, K310}, \
    {K70, K40, K41, K71, K82, K102, K83, K93, K74, K94, K75, K85, K56, K37, K28, K49, K59, K410, K610}, \
    {K60, K50, K51, K61, K92, K84, K66, K47, K57, K08, K18, K98, K108, K510} \
}

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    /*
        EACH LINE IS EACH ROW. 
     */
    [0] = LAYOUT_unix_119_ansi(
        KC_NO           , KC_NO     ,KC_F1, KC_F2, KC_F3, KC_F4     , KC_F5, KC_F6, KC_F7, KC_F8    , KC_F9, KC_F10, KC_F11, KC_F12     , KC_PSCR, KC_SCRL, KC_PAUS     ,KC_MUTE, KC_VOLD, KC_VOLU, KC_SLEP, 
        KC_NO, KC_NO    , KC_ESC    , KC_1, KC_2, KC_3, KC_4, KC_5  , KC_6, KC_7, KC_8, KC_9, KC_0,KC_MINS, KC_EQL, KC_BSLS, KC_GRV     , KC_INS , KC_HOME, KC_PGUP     ,KC_NUM , KC_PSLS, KC_PAST, KC_PMNS, 
        KC_NO, KC_NO    , KC_TAB    , KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y,  KC_U,  KC_I,   KC_O,   KC_P,   KC_LBRC, KC_RBRC, KC_BSPC     , KC_DEL , KC_END , KC_PGDN     ,KC_P7  , KC_P8  , KC_P9  , KC_PPLS,
        KC_NO, KC_NO    , KC_LCTL   , KC_A,   KC_S,  KC_D,  KC_F,  KC_G,  KC_H,  KC_J,  KC_K,   KC_L,   KC_SCLN,KC_QUOT,     KC_ENT     ,                                KC_P4  , KC_P5  , KC_P6           , 
        KC_NO, KC_NO    , KC_LSFT   , KC_Z,   KC_X,  KC_C,  KC_V,  KC_B,  KC_N,  KC_M,  KC_COMM,KC_DOT, KC_SLSH,            KC_RSFT     ,          KC_UP  ,              KC_1   , KC_2   , KC_3   , KC_PENT,
        KC_NO, KC_NO    , KC_CAPS, KC_LALT, KC_LGUI,                     KC_SPC,                    KC_RGUI   , MO(1)     , KC_RALT     , KC_LEFT, KC_DOWN, KC_RIGHT    ,KC_P0  , KC_PDOT

    ),
    [1] = LAYOUT_unix_119_ansi(
        KC_TRNS         , KC_TRNS   ,KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS  , KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS, KC_TRNS   ,KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS       , KC_TRNS, KC_TRNS, KC_TRNS   ,KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_UP, KC_TRNS, KC_TRNS         , KC_TRNS, KC_TRNS, KC_TRNS   ,KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LEFT, KC_RIGHT, KC_TRNS      ,                              KC_TRNS, KC_TRNS, KC_TRNS         , 
        KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_DOWN,            KC_TRNS     ,          KC_TRNS,            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS,                     KC_TRNS,                    KC_TRNS   , KC_TRNS   , KC_TRNS   , KC_TRNS,     KC_TRNS, KC_TRNS ,KC_TRNS,   KC_TRNS, KC_TRNS


    ),
    [2] = LAYOUT_unix_119_ansi(
        KC_TRNS         , KC_TRNS   ,KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS  , KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS, KC_TRNS   ,KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS       , KC_TRNS, KC_TRNS, KC_TRNS   ,KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS       , KC_TRNS, KC_TRNS, KC_TRNS   ,KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS       ,                              KC_TRNS, KC_TRNS, KC_TRNS         , 
        KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,            KC_TRNS     ,          KC_TRNS,            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS,                     KC_TRNS,                    KC_TRNS   , KC_TRNS   , KC_TRNS   , KC_TRNS,     KC_TRNS, KC_TRNS ,KC_TRNS,   KC_TRNS, KC_TRNS


    ),
    [3] = LAYOUT_unix_119_ansi(
        KC_TRNS         , KC_TRNS   ,KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS  , KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS, KC_TRNS   ,KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS , KC_TRNS, KC_TRNS      , KC_TRNS, KC_TRNS, KC_TRNS   ,KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS       , KC_TRNS, KC_TRNS, KC_TRNS   ,KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS       ,                              KC_TRNS, KC_TRNS, KC_TRNS         , 
        KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,            KC_TRNS     ,          KC_TRNS,            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS   , KC_TRNS, KC_TRNS,                     KC_TRNS,                    KC_TRNS   , KC_TRNS   , KC_TRNS   , KC_TRNS,     KC_TRNS, KC_TRNS ,KC_TRNS,   KC_TRNS, KC_TRNS


    ) 
};
